services:
  yappinglevel:
    build: .
    container_name: yappinglevel
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    working_dir: /usr/src/app
    command: ["yarn", "start"]
    env_file: ./.env
    environment:
      BOT_TOKEN: $BOT_TOKEN
      BOT_SERVER: $BOT_SERVER
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: botdb
      DB_HOST: db
      DB_PORT: 5432
      NODE_ENV: production

  db:
    image: postgres
    container_name: yappingleveldb
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d botdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: ./.env
    environment:
      POSTGRES_DB: botdb
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql